services:
  api:
    build: .
    container_name: fastapi
    env_file:
      - .env.docker
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - general

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=schedule
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general

  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - general

  rabbitmq:
    image: rabbitmq:3.13.6-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - general

volumes:
  postgres_data:
  redis_data:

networks:
  general:
    driver: bridge
